# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: npm install && npm run build
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./dist
